### ISSUE TITLE
[Bounty 2] Retire libsodium in Core Wallet

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/dev#11] opened 2019-02-14 19:26 UTC
libsodium is a cryptographic library currently used in the Core Wallet. It was introduced by Equihash implementation from Zcash. However it's a kind of overkill as the only feature we are using is blake2b digest. If we can replace libsodium with a more lightweight blake2b library, not only the build time but also the binary size can reduce.

[lib2b](https://github.com/BLAKE2/libb2) is a possible replacement. Note that some library may not offer options for personalized string, which is essential for Equihash-BTG, for example, openssl.

Requirements

1. A working Core Wallet with libsodium retired
2. Update building related documents under `doc/`
4. Pass all the tests

**Comment by gkostadinov** [comment] 2019-02-17 13:28
Created a pull request for the bounty: [https://github.com/BTCGPU/BTCGPU/pull/369](https://github.com/BTCGPU/BTCGPU/pull/369)

All tests pass, updated docs and replaced libsodium with libb2.

**Comment by h4x3rotab** [comment] 2019-02-21 02:25
Great work! I didn't notice there are so many troubles regarding to cross-compilation. I would like to raise the amount for this bounty by $100 as a big thank you!

**Comment by gkostadinov** [comment] 2019-02-21 17:04
Just saw that the PR has been merged. That's great. I am available if there are any issues with the merge.

Here is my BTG address for the bounty:

btg1qkm59lpj07fplp4tnn72h6pl0h7nmsf24us5nxv
![btg_address_qr](https://user-images.githubusercontent.com/1151296/53186989-c5589300-360a-11e9-9663-67ae6a756ad2.png) 

or

ASXbEoohPDpU8HVaB9BTRJ6Ln9p9vmADnu
![btg_address_qr2](https://user-images.githubusercontent.com/1151296/53188204-8841d000-360d-11e9-8de0-c689f9bfdf10.png)

**Comment by h4x3rotab** [comment] 2019-02-22 03:27
Hi @gkostadinov, just re-enabled travis-ci build. It looks like the patch to linux x86 also needs to be apply to win32/64. Please check the build log:

https://travis-ci.org/BTCGPU/BTCGPU/jobs/496505034

**Comment by gkostadinov** [comment] 2019-02-22 13:41
Ok, so, this issue was harder to reproduce than I initially thought and took me a little while. I tested the changes on the following setups:
- Ubuntu 18 PC
- Windows 10 PC with Bash for Windows
- Windows 10 PC with Ubuntu 14 VM
- Mac OS

And none of the them reproduced the issue.

The only way I managed to reproduce it was when I decided to strictly follow the commands from the Travis build logs on a fresh Ubuntu 14 VM. The issue is that the Travis build environment somehow adds a carriage return symbol `\r` to the CPU ID which then fails the bitwise operation on the CPU reg.

The latest pull request should fix that.

**Comment by h4x3rotab** [comment] 2019-02-24 15:06
Nice. It's finally fixed by your PR.

Thank you very much for the contribution! I've sent the bounty to your second address (ASXbEoohPDpU8HVaB9BTRJ6Ln9p9vmADnu).

txid: [cd4b2dec18abae14166fdf143a9f527812b2f7aa4adec05d93073ae81ba79bba](https://explorer.bitcoingold.org/insight/tx/cd4b2dec18abae14166fdf143a9f527812b2f7aa4adec05d93073ae81ba79bba)

**Closed as completed** 2019-11-13 12:17 UTC
Labels: Core, bounty
